import{initializeApp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut,sendPasswordResetEmail,setPersistence,browserLocalPersistence}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import{getFirestore,doc,getDoc,collection,query,where,getDocs,orderBy,limit}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
const $=id=>document.getElementById(id),cfg=window.WILDENHORST_FIREBASE||{};let auth,db,user,profile,season;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){$(id)?.classList.remove('hidden')}function hide(id){$(id)?.classList.add('hidden')}
function admin(){return profile?.role==='admin'||profile?.role==='headAdmin'}function head(){return profile?.role==='headAdmin'}
function dateText(k){if(!k)return'';const[y,m,d]=k.split('-').map(Number);return new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(y,m-1,d,12))}
if(!cfg.configured){show('setup')}else{const app=initializeApp(cfg);auth=getAuth(app);db=getFirestore(app);setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,authChanged)}
async function authChanged(u){if(!u){user=profile=season=null;hide('main');hide('setup');show('login');return}user=u;const s=await getDoc(doc(db,'users',u.uid));if(!s.exists()||s.data().status!=='active'){await signOut(auth);return}profile={id:s.id,...s.data()};const qs=await getDocs(query(collection(db,'seasons'),where('active','==',true),limit(1)));season=qs.empty?null:{id:qs.docs[0].id,...qs.docs[0].data()};hide('login');show('main');go('home')}
$('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(_){const m=$('loginMessage');m.textContent='Inloggen is niet gelukt. Controleer e-mailadres en wachtwoord.';m.className='message error'}});
$('forgotPassword')?.addEventListener('click',async()=>{const e=$('email').value.trim(),m=$('loginMessage');if(!e){m.textContent='Vul eerst je e-mailadres in.';m.className='message error';return}try{await sendPasswordResetEmail(auth,e);m.textContent='Er is een resetmail verstuurd.';m.className='message'}catch(_){m.textContent='De resetmail kon niet worden verstuurd.';m.className='message error'}});
$('forgotLogin')?.addEventListener('click',()=>$('forgotLoginDialog').showModal());document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));
function nav(r){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===r))}function go(r){nav(r);if(r==='home')home();if(r==='couple')couple();if(r==='saturday')saturday();if(r==='standings')standings();if(r==='more')more()}
function home(){const n=profile?.firstName||profile?.displayName||'';$('screen').innerHTML=`<section class="hero"><h1>Welkom${n?', '+esc(n):''}</h1><p>${esc(season?.name||'Seizoen 2026/2027')}</p><div class="pills"><span class="pill">🎾 zaterdag 10:00–12:00</span><span class="pill">⏰ sluit vrijdag 18:00</span><span class="pill">2 banen standaard</span></div></section>${admin()?'<div class="adminbar"><b>⚙️ Beheerder</b><button id="beheer">Open beheer</button></div>':''}<div class="tiles"><button class="tile" data-go="couple">👥<strong>Mijn koppel</strong><small>Speler en reserve per zaterdag.</small></button><button class="tile" data-go="saturday">🎾<strong>Komende zaterdag</strong><small>Spelers, vervangers en baanindeling.</small></button><button class="tile" data-go="standings">🏆<strong>Stand</strong><small>Punten per koppel.</small></button><button class="tile" data-go="more">ℹ️<strong>Uitleg & gegevens</strong><small>Spelregels en eigen gegevens.</small></button></div>`;$('screen').querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('beheer')?.addEventListener('click',beheer)}
async function playDates(){if(!season)return[];const s=await getDocs(query(collection(db,'seasons',season.id,'playDates'),orderBy('dateKey')));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function couple(){$('screen').innerHTML='<div class="card"><h2>Mijn koppel</h2><p>Laden…</p></div>';if(!profile?.coupleId){$('screen').innerHTML='<div class="card"><h2>Mijn koppel</h2><p>Nog geen koppel gekoppeld.</p></div>';return}const c=await getDoc(doc(db,'seasons',season.id,'couples',profile.coupleId)),dates=await playDates();const cp=c.exists()?c.data():{};let html=`<div class="card"><h2>${esc(cp.name||'Mijn koppel')}</h2><p>Beide koppelleden kunnen wijzigen tot vrijdag 18:00. Daarna alleen de beheerder.</p></div>`;for(const d of dates.slice(0,10)){const p=await getDoc(doc(db,'seasons',season.id,'playDates',d.id,'couplePlans',profile.coupleId)),x=p.exists()?p.data():{};html+=`<div class="date-card"><div class="date-head"><b>${esc(dateText(d.dateKey))}</b><span class="status">${x.locked?'Vergrendeld':'Open'}</span></div><div class="row"><span>${esc(x.playerName||'Nog niet ingepland')}</span><span class="status green">${esc(x.playerStatus||'Speelt')}</span></div><div class="row"><span>${esc(x.reserveName||'Partner')}</span><span class="status amber">${esc(x.reserveStatus||'Reserve')}</span></div></div>`}$('screen').innerHTML=html}
async function saturday(){$('screen').innerHTML='<div class="card"><h2>Zaterdag</h2><p>Laden…</p></div>';const ds=await playDates(),now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,d=ds.find(x=>x.dateKey>=today&&x.status!=='cancelled')||ds.at(-1);if(!d){$('screen').innerHTML='<div class="card">Nog geen speelzaterdag ingesteld.</div>';return}const ls=await getDoc(doc(db,'seasons',season.id,'playDates',d.id,'public','lineup')),l=ls.exists()?ls.data():null;$('screen').innerHTML=`<section class="hero"><h1>${esc(dateText(d.dateKey))}</h1><p>${esc(d.startTime||'10:00')}–${esc(d.endTime||'12:00')}</p>${l?.changedAfterPublish?'<div class="message">⚠️ Indeling gewijzigd</div>':''}</section>${!l?.published?'<div class="card"><b>Indeling is nog niet bekend.</b></div>':(l.courts||[]).map(c=>`<div class="court-card"><h3>Baan ${esc(c.number)}</h3><div class="match">${esc((c.teamA||[]).join(' & '))}<br>—<br>${esc((c.teamB||[]).join(' & '))}</div></div>`).join('')}${profile?.participantType==='fixed'?'<button disabled>Uitslag invoeren — koppelen na Firebase Functions</button>':''}`}
async function standings(){$('screen').innerHTML='<div class="card"><h2>Stand</h2><p>Laden…</p></div>';if(!season)return;const s=await getDocs(query(collection(db,'seasons',season.id,'standings'),orderBy('points','desc'))),rows=s.docs.map((d,i)=>({rank:i+1,...d.data()}));$('screen').innerHTML='<h2>🏆 Stand</h2>'+((rows.map(r=>`<div class="standing"><span class="rank">${r.rank}</span><div><b>${esc(r.coupleName||'Koppel')}</b><br><small>${Number(r.gamesFor||0)} games voor</small></div><span class="points">${Number(r.points||0).toFixed(1).replace('.0','')} pt</span></div>`).join(''))||'<div class="card">Nog geen uitslagen verwerkt.</div>')}
function more(){$('screen').innerHTML=`<div class="tiles"><button class="tile" id="data">👤<strong>Mijn gegevens</strong><small>Contactgegevens bekijken; enkelspelvoorkeur.</small></button><button class="tile" id="rules">📘<strong>Uitleg / spelregels</strong><small>Planning, vervangers, punten en uitslagen.</small></button>${admin()?'<button class="tile" id="admin">⚙️<strong>Beheer</strong><small>Seizoen, spelers, koppels, banen, uitslagen, betalingen.</small></button>':''}<button class="tile" id="logout">🚪<strong>Uitloggen</strong></button></div>`;$('rules').onclick=rules;$('admin')?.addEventListener('click',beheer);$('logout').onclick=()=>signOut(auth);$('data').onclick=data}
function data(){$('screen').innerHTML=`<div class="card"><h2>Mijn gegevens</h2><div class="formgrid"><div><label>Naam</label><div class="readonly">${esc(profile?.displayName||'')}</div></div><div><label>E-mailadres / inlognaam</label><div class="readonly">${esc(user?.email||'')}</div></div><div><label>Telefoon</label><div class="readonly">${esc(profile?.phone||'')}</div></div><div><label>Wil enkelspel spelen?</label><div class="readonly">${profile?.singlesPreference==='yes'?'Ja':'Nee'}</div></div></div><p>NAW/contactgegevens alleen door beheerder te wijzigen.</p></div>`}
function rules(){$('screen').innerHTML='<div class="card"><h2>Uitleg / Begrippen / Spelregels</h2><h3>Planning</h3><p>Per zaterdag speelt normaal één speler van ieder koppel en staat de partner reserve. De planning sluit vrijdag om 18:00.</p><h3>Vervanger</h3><p>Alleen nodig als beide spelers van een koppel niet kunnen. Prioriteit: niet-spelende vaste speler → reserve → andere vervanger.</p><h3>Punten</h3><p>Stand per koppel. Iedere gewonnen set is 1 punt. Met een vervanger maximaal 2 punten die zaterdag.</p><h3>Enkelspel</h3><p>Mag worden gespeeld, maar levert 0 competitiepunten op.</p><h3>WhatsApp</h3><p>De app opent alleen een voorgesteld bericht; de gebruiker verstuurt zelf.</p></div>'}
function beheer(){if(!admin())return;const s=$('screen');s.innerHTML=`<div class="adminbar"><b>⚙️ Beheer</b><button class="secondary" id="close">Sluiten</button></div><div class="admintabs"><button class="active" data-a="season">Seizoen</button><button data-a="players">Spelers & koppels</button><button data-a="lineup">Baanindeling</button><button data-a="results">Uitslagen</button><button data-a="payments">Betalingen</button>${head()?'<button data-a="admins">Beheerders</button>':''}<button data-a="rules">Uitleg</button></div><div id="ap"></div>`;$('close').onclick=()=>go('home');s.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{s.querySelectorAll('[data-a]').forEach(x=>x.classList.toggle('active',x===b));ap(b.dataset.a)});ap('season')}
function ap(t){const x={season:'<div class="admin-card"><h2>Seizoen</h2><p>2026/2027 · zaterdag 10:00–12:00 · standaard 2 banen · sluit vrijdag 18:00. Per zaterdag kan beheerder afwijken.</p></div>',players:'<div class="admin-card"><h2>Spelers & koppels</h2><p>NAW/contact, actief/reserve/inactief, koppels, speelsterkte 1–9 en betaalpositie. E-mailadres is ook Firebase-inlognaam.</p></div>',lineup:'<div class="admin-card"><h2>Baanindeling</h2><p>Per baan: Dubbel (4), Enkel (2) of niet gebruiken. Mobiel wisselen wordt tik-op-speler → tik-op-andere-speler.</p><button disabled>✓ Indeling zichtbaar maken voor iedereen</button></div>',results:'<div class="admin-card"><h2>Uitslagen</h2><p>Vaste deelnemers mogen invoeren; na opslaan alleen beheerder corrigeren. Punten worden server-side berekend.</p></div>',payments:'<div class="admin-card"><h2>Betalingen</h2><p>Alleen beheerder. 2026/27: alle 16 vaste spelers gelijk aandeel.</p></div>',admins:'<div class="admin-card"><h2>Beheerders</h2><p>Alleen hoofdbeheerder kan rollen toevoegen/verwijderen.</p></div>',rules:'<div class="admin-card"><h2>Uitleg / spelregels</h2><p>De afspraken blijven in de app gedocumenteerd.</p></div>'};$('ap').innerHTML=x[t]||''}
